stages:
- stage: BuildDev
  displayName: Build-Dev
  jobs:
  - job: Build
    pool:
      vmImage: 'windows-latest'
    steps:
    - template: StepBuildNetCore.yaml
      parameters: 
        projectsolution: ${{ parameters.projectsolution }} 
        projectsolution: ${{ parameters.argumentsbuild }} 
    #- template: StepHDIVSecurity.yaml
    - template: StepPublishArtifactory.yaml