apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\Users\hohn\kompose.exe convert -f C:\Users\hohn\OneDrive - GFT
      Technologies SE\Documents\gft\comunidadeGFT\4-POCs\2-DOING\RASP\RepoGitHub\Hdiv\hdiv-console-web\docker\docker-compose.yml
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: console
  name: console
spec:
  ports:
  - name: "8089"
    port: 8089
    targetPort: 8080
  - name: "8443"
    port: 8443
    targetPort: 8443
  selector:
    io.kompose.service: console
status:
  loadBalancer: {}
