apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\Users\hohn\kompose.exe convert -f C:\Users\hohn\OneDrive - GFT
      Technologies SE\Documents\gft\comunidadeGFT\4-POCs\2-DOING\RASP\RepoGitHub\Hdiv\hdiv-console-web\docker\docker-compose.yml
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: console
  name: console
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: console
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: C:\Users\hohn\kompose.exe convert -f C:\Users\hohn\OneDrive -
          GFT Technologies SE\Documents\gft\comunidadeGFT\4-POCs\2-DOING\RASP\RepoGitHub\Hdiv\hdiv-console-web\docker\docker-compose.yml
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: console
    spec:
      containers:
      - image: tomcat:8.5.51-jdk11-openjdk
        imagePullPolicy: ""
        livenessProbe:
          exec:
            command:
            - curl
            - -f
            - http://localhost:8080/hdiv-console-services
          failureThreshold: 3
          periodSeconds: 90
          timeoutSeconds: 10
        name: console
        ports:
        - containerPort: 8080
        - containerPort: 8443
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
