apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\Users\hohn\kompose.exe convert -f C:\Users\hohn\OneDrive - GFT
      Technologies SE\Documents\gft\comunidadeGFT\4-POCs\2-DOING\RASP\RepoGitHub\Hdiv\hdiv-console-web\docker\docker-compose.yml
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: console
  name: console
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: console
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: C:\Users\hohn\kompose.exe convert -f C:\Users\hohn\OneDrive -
          GFT Technologies SE\Documents\gft\comunidadeGFT\4-POCs\2-DOING\RASP\RepoGitHub\Hdiv\hdiv-console-web\docker\docker-compose.yml
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: console
    spec:
      containers:
      - image: tomcat:8.5.51-jdk11-openjdk
        imagePullPolicy: ""
        livenessProbe:
          exec:
            command:
            - curl
            - -f
            - http://localhost:8080/hdiv-console-services
          failureThreshold: 3
          periodSeconds: 90
          timeoutSeconds: 10
        name: console
        ports:
        - containerPort: 8080
        - containerPort: 8443
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\Users\hohn\kompose.exe convert -f C:\Users\hohn\OneDrive - GFT
      Technologies SE\Documents\gft\comunidadeGFT\4-POCs\2-DOING\RASP\RepoGitHub\Hdiv\hdiv-console-web\docker\docker-compose.yml
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: console
  name: console
spec:
  type: LoadBalancer
  ports:
  - name: "8089"
    port: 8089
    targetPort: 8080
  - name: "8443"
    port: 8443
    targetPort: 8443
  selector:
    io.kompose.service: console
status:
  loadBalancer: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\Users\hohn\kompose.exe convert -f C:\Users\hohn\OneDrive - GFT
      Technologies SE\Documents\gft\comunidadeGFT\4-POCs\2-DOING\RASP\RepoGitHub\Hdiv\hdiv-console-web\docker\docker-compose.yml
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: postgres
  name: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: postgres
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: C:\Users\hohn\kompose.exe convert -f C:\Users\hohn\OneDrive -
          GFT Technologies SE\Documents\gft\comunidadeGFT\4-POCs\2-DOING\RASP\RepoGitHub\Hdiv\hdiv-console-web\docker\docker-compose.yml
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: postgres
    spec:
      containers:
      - env:
        - name: POSTGRES_DB
          value: hdiventerprise
        - name: POSTGRES_PASSWORD
          value: hdiv-enterprise
        - name: POSTGRES_USER
          value: hdiv
        image: postgres:9.6.12-alpine
        imagePullPolicy: ""
        name: postgres
        ports:
        - containerPort: 5432
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\Users\hohn\kompose.exe convert -f C:\Users\hohn\OneDrive - GFT
      Technologies SE\Documents\gft\comunidadeGFT\4-POCs\2-DOING\RASP\RepoGitHub\Hdiv\hdiv-console-web\docker\docker-compose.yml
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: postgres
  name: postgres
spec:
  ports:
  - name: "5432"
    port: 5432
    targetPort: 5432
  selector:
    io.kompose.service: postgres
status:
  loadBalancer: {}