version: '3'
services:
   console:
      image: tomcat:8.5.51-jdk11-openjdk
      restart: always
      ports:
         - "8089:8080"
         - "8443:8443"
      depends_on:
         - postgres
      volumes:
         - ../console/server/webapps:/usr/local/tomcat/webapps
         - ../license:/usr/local/tomcat/hdiv-config
         - ./setenv.sh:/usr/local/tomcat/bin/setenv.sh
         - ./logs:/usr/local/tomcat/logs
         - ../console/server/conf/server.xml:/usr/local/tomcat/conf/server.xml
         - ../console/server/conf/hdiv-console.jks:/usr/local/tomcat/conf/hdiv-console.jks
      healthcheck:
         test: ["CMD", "curl", "-f", "http://localhost:8080/hdiv-console-services"]
         interval: 1m30s
         timeout: 10s
         retries: 3

   postgres:
      image: postgres:9.6.12-alpine
      restart: always
      expose:
         - "5432"
      volumes:
         - ./data:/var/lib/postgresql/data
      environment:
         - POSTGRES_USER=hdiv
         - POSTGRES_PASSWORD=hdiv-enterprise
         - POSTGRES_DB=hdiventerprise
