apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\Users\hohn\kompose.exe convert -f C:\Users\hohn\OneDrive - GFT
      Technologies SE\Documents\gft\comunidadeGFT\4-POCs\2-DOING\RASP\RepoGitHub\Hdiv\hdiv-console-web\docker\docker-compose.yml
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: postgres
  name: postgres
spec:
  ports:
  - name: "5432"
    port: 5432
    targetPort: 5432
  selector:
    io.kompose.service: postgres
status:
  loadBalancer: {}
