# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
  branches:
    include:
    - dev
    - qa
    - prod

variables:
  solution: 'Pocs.HealthCheck/Pocs.HealthCheck.csproj'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'


stages:
- ${{ if contains(variables['Build.SourceBranch'], 'dev') }}:  
  - stage: BuildDev
    displayName: Build-Dev
    jobs:
    - job: Build
      pool:
        vmImage: 'windows-latest'
      steps:
      - task: DotNetCoreCLI@2
        displayName: 'dotnet build'
        inputs:
          command: 'publish'
          publishWebProjects: true
          arguments: '/p:Configuration=Release'
      - task: CopyFiles@2
        inputs:
          SourceFolder: 'HealthCheck/'
          Contents: 'Pocs.HealthCheck/*.yaml'
          TargetFolder: '$(Agent.BuildDirectory)/Pocs.HealthCheck'
          CleanTargetFolder: true
          OverWrite: true
      - task: CopyFiles@2
        inputs:
          SourceFolder: 'HealthCheck/'
          Contents: 'Pocs.HealthCheck/Dockerfile'
          TargetFolder: '$(Agent.BuildDirectory)/Pocs.HealthCheck'
          OverWrite: true
      - script: 'sed -i ''s/{{TAG_VERSION}}/$(Build.BuildId)/g'' $(Agent.BuildDirectory)/Pocs.HealthCheck/**.yaml'
        displayName: 'Command Line Script'
      - task: ArchiveFiles@2
        inputs:
          rootFolderOrFile: '$(Agent.BuildDirectory)/'
          includeRootFolder: true
          archiveType: 'zip'
          archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
          replaceExistingArchive: true
      - task: PublishBuildArtifacts@1
        displayName: 'Publish Artifact'
        inputs:
          PathtoPublish: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
          ArtifactName: '$(Parameters.ArtifactName)'
          publishLocation: 'Container'
        condition: succeededOrFailed()

  - stage: Foundation
    dependsOn: []
    ${{ if contains(variables['Build.SourceBranch'], 'dev') }}:
      condition: and(succeeded(), true)
    ${{ if contains(variables['Build.SourceBranch'], 'hotfix') }}:  
      condition: false
    ${{ if contains(variables['Build.SourceBranch'], 'prod') }}:  
      condition: false
    ${{ if contains(variables['Build.SourceBranch'], 'qa') }}:  
      condition: false
    jobs:
    - deployment: release_dev
      variables: 
        - name: ResourceGroupName
          value: 'pocrasp-dev'
        - name: 'azureSubscription'
          value: 'Assinatura do Visual Studio Enterprise – MPN(a45048d3-69a8-4e2d-89a9-4585441c96f6)'

      pool:
        vmImage: ubuntu-16.04
      environment: dev
      strategy:
        runOnce:
          deploy:
            steps:
            - checkout: self
            - script: echo running UnitTest
            - task: TerraformInstaller@0
              displayName: 'TF install'
              inputs:
                terraformVersion: '0.12.3'

            - task: TerraformTaskV1@0
              displayName: 'TF Initi'
              inputs:
                provider: 'azurerm'
                command: 'init'
                workingDirectory: 'tf'
                backendServiceArm: ${{ variables.azureSubscription  }}
                backendAzureRmResourceGroupName: 'storage'
                backendAzureRmStorageAccountName: 'ststudyheider'
                backendAzureRmContainerName: 'terra'
                backendAzureRmKey: 'pocrasp'

            - task: TerraformTaskV1@0
              displayName: 'TF Plan'
              inputs:
                provider: 'azurerm'
                command: 'plan'
                workingDirectory: 'tf'
                commandOptions: '-out dev'
                environmentServiceNameAzureRM: ${{ variables.azureSubscription  }}

            - task: TerraformTaskV1@0
              displayName: 'TF Apply'
              inputs:
                provider: 'azurerm'
                command: 'apply'
                workingDirectory: 'tf'
                commandOptions: 'dev'
                environmentServiceNameAzureRM: ${{ variables.azureSubscription  }}

  - stage: BuildImage
    displayName: Build-img
    dependsOn: Foundation
    jobs:
    - job: Build
      pool:
        vmImage: ubuntu-16.04
      steps:
      - task: Docker@2
        inputs:
          containerRegistry: 'pocraspacr'
          command: 'login'
      - task: Docker@2
        inputs:
          containerRegistry: 'pocraspacr'
          repository: 'rasp'
          command: 'buildAndPush'
          Dockerfile: '$(Agent.BuildDirectory)/Pocs.HealthCheck/Dockerfile'
          tags: |
            $(Build.BuildId)
            latest

  - stage: DeployAKS
    dependsOn: BuildImage
    jobs:
    - deployment: release_dev
      ${{ if contains(variables['Build.SourceBranch'], 'dev') }}:
        condition: and(succeeded(), true)
      ${{ if contains(variables['Build.SourceBranch'], 'hotfix') }}:  
        condition: false
      ${{ if contains(variables['Build.SourceBranch'], 'prod') }}:  
        condition: false
      ${{ if contains(variables['Build.SourceBranch'], 'qa') }}:  
        condition: false
      variables: 
        - name: ENVIRONMENT
          value: 'Development'
        - name: 'azureSubscription'
          value: 'Assinatura do Visual Studio Enterprise – MPN(a45048d3-69a8-4e2d-89a9-4585441c96f6)'

      pool:
        vmImage: ubuntu-16.04
      environment: dev
      strategy:
        runOnce:
          deploy:
            steps:
            - checkout: self
            - script: echo running UnitTest
            - task: ExtractFiles@1
              inputs:
                archiveFilePatterns: '**/*.zip'
                destinationFolder: 'AppToPublish'
                cleanDestinationFolder: false
                overwriteExistingFiles: true
            - task: replacetokens@3
              inputs:
                rootDirectory: '$(Agent.BuildDirectory)/Pocs.HealthCheck'
                targetFiles: 'BuildImg-Container.yaml'
                encoding: 'auto'
                writeBOM: true
                actionOnMissing: 'warn'
                keepToken: false
                tokenPrefix: '{{'
                tokenSuffix: '}}'
                useLegacyPattern: false
                enableTransforms: false
                enableTelemetry: true
            - task: Kubernetes@1
              inputs:
                connectionType: 'Kubernetes Service Connection'
                kubernetesServiceEndpoint: 'AKSRASP'
                namespace: 'pocrasp'
                command: 'apply'
                useConfigurationFile: true
                configuration: '$(Agent.BuildDirectory)/Pocs.HealthCheck/BuildImg-Container.yaml'
                secretType: 'dockerRegistry'
                containerRegistryType: 'Azure Container Registry'